name: vllm
channels:
  - https://conda.anaconda.org/pytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py39hbdd6827_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.18=hd6dcaed_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.0=py39h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - python=3.9.19=h955ad1f_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=2_cp39
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - aiohttp==3.9.5
      - aioprometheus==23.12.0
      - aiosignal==1.3.1
      - airportsdata==20250224
      - albucore==0.0.21
      - albumentations==1.1.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrs==23.2.0
      - autoawq==0.2.8
      - av==14.0.0
      - blake3==1.0.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.0
      - compressed-tensors==0.10.1
      - configargparse==1.7
      - contourpy==1.3.0
      - cupy-cuda12x==13.4.0
      - cycler==0.12.1
      - datasets==3.3.2
      - decorator==5.1.1
      - deepseek-vl==1.0.0
      - deepseek-vl2==1.0.0
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.6.1
      - einops==0.8.0
      - email-validator==2.2.0
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.1
      - executing==2.1.0
      - fastapi==0.115.13
      - fastapi-cli==0.0.7
      - fastprogress==1.0.3
      - fastrlock==0.8.3
      - filelock==3.17.0
      - flask==3.1.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gensim==4.3.3
      - gguf==0.17.1
      - googleapis-common-protos==1.70.0
      - grpcio==1.68.1
      - h11==0.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.33.0
      - idna==3.7
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.4
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipython==8.18.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lark==1.2.2
      - lazy-loader==0.4
      - lit==18.1.8
      - llguidance==0.7.30
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistral-common==1.6.2
      - modelscope==1.23.1
      - mpmath==1.3.0
      - msgpack==1.0.8
      - msgspec==0.19.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.65.4
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.11.0.86
      - opennmt-py==2.2.0
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-exporter-otlp-proto-http==1.34.1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentelemetry-semantic-conventions-ai==0.4.9
      - orjson==3.10.6
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post5
      - pillow==10.4.0
      - pluggy==1.5.0
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.48
      - protobuf==5.27.2
      - psutil==6.0.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pyonmttok==1.37.1
      - pyparsing==3.1.4
      - pytest==8.3.5
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-fast-transformers==0.4.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.2.1
      - quantile-python==1.1
      - qudida==0.0.4
      - qwen-vl-utils==0.0.8
      - ray==2.47.1
      - rdkit==2024.3.6
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - rich-toolkit==0.14.7
      - rpds-py==0.19.0
      - safetensors==0.4.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simsimd==6.2.1
      - six==1.16.0
      - smart-open==7.1.0
      - smilespe==0.0.3
      - sniffio==1.3.1
      - socksio==1.0.0
      - stack-data==0.6.3
      - starlette==0.46.2
      - stringzilla==3.11.2
      - sympy==1.14.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tiktoken==0.7.0
      - timm==1.0.14
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchtext==0.5.0
      - torchvision==0.22.0
      - tqdm==4.66.4
      - transformers==4.52.4
      - triton==3.3.0
      - trl==0.15.2
      - typer==0.12.3
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.2
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - vllm==0.9.1
      - vllm-flash-attn==2.5.9
      - waitress==3.0.2
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.20.1
      - zstandard==0.23.0
prefix: /zengdaojian/zhangjia/anaconda3/envs/vllm
